Fix the following error when compiling SDL game pad support on OSX: "OpenPilot/ground/openpilotgcs/src/libs/sdlgamepad/sdlgamepad.pro -spec macx-g++ CONFIG+=release\ silent -o Makefile ) && make -f Makefile make[4]: Entering directory `/Users/kevinfinisterre/Desktop/OpenPilot/build/openpilotgcs_release/src/libs/sdlgamepad' compiling ../../../../../ground/openpilotgcs/src/libs/sdlgamepad/sdlgamepad.cpp In file included from ../../../../../ground/openpilotgcs/src/libs/sdlgamepad/sdlgamepad.cpp:22: ../../../../../ground/openpilotgcs/src/libs/sdlgamepad/sdlgamepad.h:28:10: fatal error: 'SDL/SDL.h' file not found
Please use homebrew to install SDL into /usr/local :
"$ brew install sdl
==> Downloading http://www.libsdl.org/release/SDL-1.2.15.tar.gz
==> ./configure --prefix=/usr/local/Cellar/sdl/1.2.15 --without-x
==> make install
...
$ sudo brew link --overwrite sdl
Password:
Linking /usr/local/Cellar/sdl/1.2.15... 213 symlinks created"

To prevent the warning:
"Qt5.1.1/5.1.1/clang_64/include/QtCore/qsystemdetection.h:243:6: warning: "This version of OS X is unsupported" [-W#warnings]"
edit line 242 of qsystemdetection.h in ~/Qt5.1.1/5.1.1/clang_64/include/QtCore/ to read __MAC_10_9:
instead of 10_8 per the default
242:#  if (__MAC_OS_X_VERSION_MAX_ALLOWED > __MAC_10_8)

Currently needs fixes for qDebug and qWarning errors.

: error: use of undeclared identifier
      'QT_NO_QDEBUG_MACRO'
        QSBDEBUG()